Update AsyncEventEmitter.js
An error is thrown when attempting to emit an event when no events have been defined.

e.g. create the emitter and fire emit without calling on, etc.

In my case i have an event i am calling 'initialize' however i have not defined any listeners.

TypeError: Cannot read property 'initialize' of undefined
      at TestComponent.AsyncEventEmitter.emit (sdk/node_modules/async-eventemitter/lib/AsyncEventEmitter.js:21:31)